const projects = [
  {
    name: "Pichub",
    desc: `Pichub is a social media platform that allows registered users to share images, follow other 
           users, like, comment, and send real-time messages.
               See the source code in my github repo....`,
    image: "./projects/pichub.png",
    link: "https://github.com/therealruvais/Social_Media_Application",
    target: "_blank",
  },
  {
    name: "Shoping Cart",
    desc: `This a small website which I created using Node and Express js .
               This website contains an Addproduct page in which can add a specif product and can render in the Shop page , image is generated by API.
               `,
    image: "./projects/shop.png",
    link: "https://github.com/therealruvais/node-express-shopingList",
    target: "_blank",
  },
  {
    name: "T-rex",
    desc: `This a small game which I created using javascript and p5.js library .
               This game is very simple we use spacebar to jump and we can see the score in the right section if the t-rex avatar touches an object then it's game over.  
               `,
    image: "./projects/t-rex.png",
    link: "https://github.com/therealruvais/trex-game",
    target: "_blank",
  },
  {
    name: "Landing Page",
    desc: `This a small Webpage which I created using React , three.js , react-three/fiber andreact-three/drei .
              This is a small webpage including 3d object.
               See the source code in my github repo....`,
    image: "./projects/threeejs.png",
    link: "https://github.com/therealruvais/landingPage-3js",
    target: "_blank",
  },
];

export default projects;
